vich_uploader:
    db_driver: orm

    mappings:
        boutique_image:
            uri_prefix: /uploads/boutiques
            upload_destination: "%kernel.project_dir%/public/uploads/boutiques"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        logo_image:
            uri_prefix: /uploads/logos
            upload_destination: "%kernel.project_dir%/public/uploads/logos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        produit_image:
            uri_prefix: /uploads/produits
            upload_destination: "%kernel.project_dir%/public/uploads/produits"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
